---
deployment:
  tasks:
    - export DEPLOYPATH=/home/USERNAME/APPDIR/
    - /bin/cp -R ./* $DEPLOYPATH
    - /bin/cp -R ./.next $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - cd $DEPLOYPATH && npm run build
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
